### ISSUE TITLE
pip install helics on MSYS2

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/HELICS#1101]
When using pip install helics on MSYS2 it results in an an error 
```
 ERROR: Command errored out with exit status 1:
     command: K:/msys64/mingw64/bin/python.exe -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:/Users/phlpt/AppData/Local/Temp/pip-install-ve43ghnz/helics/setup.py'"'"'; __file__='"'"'C:/Users/phlpt/AppData/Local/Temp/pip-install-ve43ghnz/helics/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record C:/Users/phlpt/AppData/Local/Temp/pip-record-q7jw8pg5/install-record.txt --single-version-externally-managed --compile --install-headers K:/msys64/mingw64/include/python3.8/helics
         cwd: C:/Users/phlpt/AppData/Local/Temp/pip-install-ve43ghnz/helics/
    Complete output (47 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.mingw-3.8
    creating build/lib.mingw-3.8/helics
    copying helics/_version.py -> build/lib.mingw-3.8/helics
    copying helics/__init__.py -> build/lib.mingw-3.8/helics
    running build_ext
    cmake version 3.16.4

    CMake suite maintained and supported by Kitware (kitware.com/cmake).
    CMake Error: The source directory "C:/Users/phlpt/AppData/Local/Temp/pip-install-ve43ghnz/helics/bundled/helics/interfaces/python" does not exist.
    Specify --help for usage, or press the help button on the CMake GUI.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:/Users/phlpt/AppData/Local/Temp/pip-install-ve43ghnz/helics/setup.py", line 117, in <module>
        setup(
      File "K:/msys64/mingw64/lib/python3.8/site-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "K:/msys64/mingw64/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "K:/msys64/mingw64/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "K:/msys64/mingw64/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "K:/msys64/mingw64/lib/python3.8/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "K:/msys64/mingw64/lib/python3.8/distutils/command/install.py", line 546, in run
        self.run_command('build')
      File "K:/msys64/mingw64/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "K:/msys64/mingw64/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "K:/msys64/mingw64/lib/python3.8/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "K:/msys64/mingw64/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "K:/msys64/mingw64/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:/Users/phlpt/AppData/Local/Temp/pip-install-ve43ghnz/helics/setup.py", line 35, in run
        self.build_extension(ext)
      File "C:/Users/phlpt/AppData/Local/Temp/pip-install-ve43ghnz/helics/setup.py", line 99, in build_extension
        subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp)
      File "K:/msys64/mingw64/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', 'C:/Users/phlpt/AppData/Local/Temp/pip-install-ve43ghnz/helics/bundled/helics/interfaces/python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:/Users/phlpt/AppData/Local/Temp/pip-install-ve43ghnz/helics/build/lib.mingw-3.8/helics', '-DCMAKE_BUILD_WITH_INSTALL_RPATH=ON', '-DHELICS_ENABLE_SWIG=OFF', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:/Users/phlpt/AppData/Local/Temp/pip-install-ve43ghnz/helics/build/lib.mingw-3.8/helics', '-A', 'x64']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: K:/msys64/mingw64/bin/python.exe -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:/Users/phlpt/AppData/Local/Temp/pip-install-ve43ghnz/helics/setup.py'"'"'; __file__='"'"'C:/Users/phlpt/AppData/Local/Temp/pip-install-ve43ghnz/helics/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record C:/Users/phlpt/AppData/Local/Temp/pip-record-q7jw8pg5/install-record.txt --single-version-externally-managed --compile --install-headers K:/msys64/mingw64/include/python3.8/helics Check the logs for full command output.

```

It would be nice if this worked to install the python libraries for helics on MSYS2

**Comment by nightlark** [comment]
It looks like the pip source package is missing the bundled copy of the python interface CMake project -- I'll try to get a working pip package up tomorrow or Friday.

**Comment by nightlark** [comment]
@phlptp the package is now on the main pypi site, so `pip install helics` should work. I think the key change is that `CMAKE_*` environment variables can be set by a user to control what generator gets used if needed.

**Comment by phlptp** [comment]
How do set those variables?

**Comment by nightlark** [comment]
They’re just regular Unix environment variables (nothing HELICS or CMake), it slightly depends on the shell used; the most common way in bash and several others is `VAR=<value>` either as a separate command or the same line before the command. For user docs the msys section should probably link to the same Unix basics guides that the Linux/macOS sections link to.

For a lot of (all?) the `CMAKE_*` options, it checks if an environment variable with the same name is set and uses that as the initial value. Any `-DCMAKE_*` arguments passed to CMake take precedence over whatever it picked up from environment variables.

**Comment by nightlark** [comment]
The mentioned change is that the pip package would run CMake with the -A argument regardless of the generator used, so I added some checks to disable adding it if the user set the generator though an environment variable to something other than VS, or if the default generator is not VS.

**Comment by phlptp** [comment]
I need to write some instructions for using it in MSYS,  what is the best way of doing that in MSYS2?  

after installing helics through pacman in MSYS 2 the pip install helics succeeds but I get this error
```
phlpt@Sirius MINGW64 ~
$ python
Python 3.8.2 (default, Feb 27 2020, 05:27:33)  [GCC 9.2.0 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import helics
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "K:/msys64/mingw64/lib/python3.8/site-packages/helics/__init__.py", line 1, in <module>
    from .helics import *
  File "K:/msys64/mingw64/lib/python3.8/site-packages/helics/helics.py", line 13, in <module>
    from . import _helics
ImportError: DLL load failed while importing _helics: The specified module could not be found.
>>>

``` 
when running python and importing helics

**Comment by phlptp** [comment]
If I haven't installed helics I get a big error but I presume that is where the requirement for setting the CMAKE_GENERATOR comes in,  But I need to put the instructions some where.

**Comment by phlptp** [comment]
I will work on that some more later today

**Comment by nightlark** [comment]
The hard requirement is having an already compiled copy of HELICS installed.

Some CMake-related environment variables that could be useful for troubleshooting are (may not be required):
- Set `CMAKE_GENERATOR` to `Unix Makefiles` if CMake is trying to default to the Visual Studio generator (if they're lucky and it defaults to `Unix Makefiles` on their system, not needed)
- Set `HELICS_ROOT` to the install prefix that HELICS was installed to, if CMake doesn't automatically pick it up (locations on the system path should be detected)

The import error looks like it could be that it isn't finding where a helicsSharedLib.dll is installed for loading the Python module? If MSYS2 acts like a normal Unix system, then that could mean helicsSharedLib.dll isn't in a folder located in `LD_LIBRARY_PATH`. If it loads shared libraries like a typical Windows machine then maybe the install location of helicsSharedLib.dll isn't listed in `PATH`.
