### ISSUE TITLE
Helics doesn't work with multiprocessing.Process on Linux

### ISSUE THREAD

**Issue by plimy** [GMLC-TDC/HELICS#2061]
**Describe the bug**
Using multiprocessing.Process to create federates crashes on Linux. But it works fine on Windows.

**What is the expected behavior?**
I expect to be able to spin up federates using multiprocessing.Process, on both Linux and Windows.

**To Reproduce**
1. Be on a Linux machine
2. pip install helics
3. python3 /path to python test/pymultiprocessing.p
```Python
# pymultiprocessing.p
from multiprocessing import Process
import multiprocessing
import helics as h
import time
from math import pi


broker_type = "zmq"

def PiSender():
    deltat = 0.01
    fedinitstring = "--federates=1"
    fedinfo = h.helicsCreateFederateInfo()
    h.helicsFederateInfoSetCoreName(fedinfo, "PiSender Federate")
    h.helicsFederateInfoSetCoreTypeFromString(fedinfo, broker_type)
    h.helicsFederateInfoSetCoreInitString(fedinfo, fedinitstring)
    h.helicsFederateInfoSetTimeProperty(fedinfo, h.helics_property_time_delta, deltat)
    vfed = h.helicsCreateValueFederate("PiSender Federate", fedinfo)
    pub = h.helicsFederateRegisterGlobalTypePublication(vfed, "PiSender", "double", "")
    h.helicsFederateEnterExecutingMode(vfed)
    for t in range(0, 10):
        val = pi + t
        currentTime = h.helicsFederateRequestTime(vfed, t+1)
        h.helicsPublicationPublishDouble(pub, val)
        time.sleep(1)

if __name__ == '__main__':
    multiprocessing.freeze_support()

    initstring = "-f 2"
    broker = h.helicsCreateBroker(broker_type, "", initstring)
    isconnected = h.helicsBrokerIsConnected(broker)
    if (isconnected == 1):
        print("Broker Connected")


    print("Making PiSender Process")
    pi_process = Process(
        target=PiSender,
        name="PiSender Process",
        args=(),
    )
    print("Starting PiSender")
    pi_process.start()

    fedinitstring = "--federates=1"
    deltat = 0.01
    fedinfo = h.helicsCreateFederateInfo()
    h.helicsFederateInfoSetCoreName(fedinfo, fedinitstring)
    h.helicsFederateInfoSetCoreTypeFromString(fedinfo, broker_type)
    h.helicsFederateInfoSetTimeProperty(fedinfo, h.helics_property_time_delta, deltat)
    vfed = h.helicsCreateValueFederate("Reciever Federate", fedinfo)
    pi_sub = h.helicsFederateRegisterSubscription(vfed, "PiSender", "")
    h.helicsFederateEnterExecutingMode(vfed)

    currentTime = -1
    last_pi_value = 0
    while currentTime <= 100:
        currentTime = h.helicsFederateRequestTime(vfed, 100)
        temp = h.helicsInputGetDouble(pi_sub)
        if (temp != last_pi_value):
            last_pi_value = temp
            print("Recieved Value {}".format(temp))

    print("Finished")
    h.helicsFederateDisconnect(vfed)
    h.helicsFederateFree(vfed)
    h.helicsCloseLibrary()
```

**Environment:**

- Operating System: Linux Ubuntu
- Version: 20.0.4.2 LTS
- Language Extension: Python
- pip install helics
   - gcc 9.3.0
   -  g++ 9.3.0
   - python 3.8.10
- HELICS version: 

```bash
$ helics_app --version
3.0.0-main-g35729b49 (2021-08-20)
```

**Additional context and information**
On Linux, zmq broker leads to an indefinite hang, using a tcp/udp broker leads to a seg fault.
The above code works without a hiccup on Windows 10.

I am uncertain as to the cause of the issue. I believe it has to do with an incompatibility between helics and fork(). As multiprocessing.Process uses fork() on Linux, and doesn't on Windows, but I am not positive that that is the case.

```bash
Broker Connected
Making PiSender Process
Starting PiSender
[2021-08-23 09:04:48.518] [console] [warning] commWarning||PiSender Federate (0)[t=-98763.2]::zmq broker connection timed out, trying again (2)
[2021-08-23 09:04:48.518] [console] [warning] commWarning||PiSender Federate (0)[t=-98763.2]::sending message to tcp://127.0.0.1:23405
[2021-08-23 09:05:08.540] [console] [error] commERROR||PiSender Federate (0)[t=-98763.2]::zmq broker connection timed out after trying 5 times (2)
[2021-08-23 09:05:08.540] [console] [error] commERROR||PiSender Federate (0)[t=-98763.2]::receiver connection failure
Process PiSender Process:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "PiMultiprocessing.py", line 18, in PiSender
    vfed = h.helicsCreateValueFederate("PiSender Federate", fedinfo)
  File "/usr/local/lib/python3.8/dist-packages/helics-3.0.0.post0-py3.8-linux-x86_64.egg/helics/capi.py", line 3204, in helicsCreateValueFederate
    raise HelicsException("[" + str(err.error_code) + "] " + ffi.string(err.message).decode())
helics.capi.HelicsException: [-1] Unable to connect to broker->unable to register federate
```

**Comment by kdheepak** [comment]
@plimy I was able to run your code successfully on my mac. So it appears to be a linux only issue.

<img width="1680" alt="Screen Shot 2021-08-23 at 11 49 22 AM" src="https://user-images.githubusercontent.com/1813121/130493463-27c63db9-a388-4055-bc96-2992c16615ca.png">

**Comment by nightlark** [comment]
This is a Python multiprocessing issue -- see discussion in https://github.com/GMLC-TDC/pyhelics/issues/30#issuecomment-905795197 for the fix if you're using multiprocessing on Linux and encounter a similar issue.
