### ISSUE TITLE
IPC core not working with PyHELICS? 

### ISSUE THREAD

**Issue by trevorhardy** [GMLC-TDC/HELICS#2621]
**Describe the bug**
Switching the advanced default example to use the IPC core fails to create federates

**What is the expected behavior?**
Since I'm running the example on a single compute node, IPC should run just as well as ZMQ.

**To Reproduce**
Change the "core_type" in the JSON config files of the Battery, Charger, and Controller of the [advanced default ](https://github.com/GMLC-TDC/HELICS-Examples/tree/main/user_guide_examples/advanced/advanced_default) to "ipc" and attempt to run.

**Environment (please complete the following information):**
Tested on
- Operating System: macOS 14.3.1
- Language Extension: Python
- Build/Install process: installed HELICS v3.5.0 via pre-compiled binaries distributed on HELICS Github page
- HELICS version: 3.5.0

```bash
$ helics_app --version
3.5.0 (2024-02-06)
```

Error message(s):
**Battery**
```
[2024-02-14 11:04:05.033] [console] [error] commERROR||battery_core (0)[connected_error]::transmitter connection failure
[2024-02-14 11:04:05.033] [console] [error] battery_core (0)[connected_error]::Unable to open broker connection -> timed out waiting for the queue to become available
Traceback (most recent call last):
  File "/Users/hard312/src/HELICS/HELICS-Examples/user_guide_examples/advanced/advanced_default/Battery.py", line 78, in <module>
    fed = h.helicsCreateValueFederateFromConfig("BatteryConfig.json")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hard312/anaconda3/envs/helics_350/lib/python3.11/site-packages/helics/capi.py", line 3635, in helicsCreateValueFederateFromConfig
    raise HelicsException("[" + str(err.error_code) + "] " + ffi.string(err.message).decode())
helics.capi.HelicsException: [-1] Unable to connect to broker->unable to register federate
```

**Charger**
```
[2024-02-14 11:04:05.043] [console] [error] charger_core (0)[connected_error]::Unable to open broker connection -> timed out waiting for the queue to become available
[2024-02-14 11:04:05.043] [console] [error] commERROR||charger_core (0)[connected_error]::transmitter connection failure
Traceback (most recent call last):
  File "/Users/hard312/src/HELICS/HELICS-Examples/user_guide_examples/advanced/advanced_default/Charger.py", line 142, in <module>
    fed = h.helicsCreateCombinationFederateFromConfig("ChargerConfig.json")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hard312/anaconda3/envs/helics_350/lib/python3.11/site-packages/helics/capi.py", line 3723, in helicsCreateCombinationFederateFromConfig
    raise HelicsException("[" + str(err.error_code) + "] " + ffi.string(err.message).decode())
helics.capi.HelicsException: [-1] Unable to connect to broker->unable to register federate

```

**Controller**
```
[2024-02-14 11:14:41.232] [console] [error] controller_core (0)[connected_error]::Unable to open broker connection -> timed out waiting for the queue to become available
[2024-02-14 11:14:41.232] [console] [error] commERROR||controller_core (0)[terminating_error]::transmitter connection failure
Traceback (most recent call last):
  File "/Users/hard312/src/HELICS/HELICS-Examples/user_guide_examples/advanced/advanced_default/Controller.py", line 52, in <module>
    fed = h.helicsCreateMessageFederateFromConfig("ControllerConfig.json")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hard312/anaconda3/envs/helics_350/lib/python3.11/site-packages/helics/capi.py", line 3678, in helicsCreateMessageFederateFromConfig
    raise HelicsException("[" + str(err.error_code) + "] " + ffi.string(err.message).decode())
helics.capi.HelicsException: [-1] Unable to connect to broker->unable to register federate

```

**Comment by trevorhardy** [comment]
Retested under HELICS and PyHELICS 3.6.0 and still fails.
